class Check < ActiveRecord::Base
  belongs_to :semester
  belongs_to :discipline
  attr_accessible :check_kind, :semester
  validates_presence_of :semester, :discipline, :check_kind

  has_enum :check_kind

  def report_kind_value
    I18n.t check_kind, :scope => 'activerecord.attributes.check.check_kind_reports'
  end
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: checks
#
# * id            :integer         not null
#   semester_id   :integer
#   discipline_id :integer
#   check_kind    :string(255)
#   created_at    :datetime        not null
#   updated_at    :datetime        not null
#   deleted_at    :datetime
#
#  Indexes:
#   index_checks_on_discipline_id  discipline_id
#   index_checks_on_semester_id    semester_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
