class Check < ActiveRecord::Base
  belongs_to :semester
  belongs_to :discipline
  attr_accessible :kind, :semester
  validates_presence_of :semester, :discipline, :kind

  has_enum :kind
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: checks
#
# * id            :integer         not null
#   semester_id   :integer
#   discipline_id :integer
#   kind          :string(255)
#   created_at    :datetime        not null
#   updated_at    :datetime        not null
#   deleted_at    :datetime
#
#  Indexes:
#   index_checks_on_discipline_id  discipline_id
#   index_checks_on_semester_id    semester_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
