class Department < ActiveRecord::Base
  belongs_to :year
  attr_accessible :abbr, :title

  has_many :subdepartments

  def self.title_by_subdepartment(title)
    YAML.load_file("#{Rails.root}/data/departments.yml").each do |department|
      return department['title'] if department['subdepartments'].map{|sd| sd['title']}.select{|sd| sd == title}
    end
  end


end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: departments
#
# * id         :integer         not null
#   title      :string(255)
#   abbr       :string(255)
#   year_id    :integer
#   created_at :datetime        not null
#   updated_at :datetime        not null
#
#  Indexes:
#   index_departments_on_year_id  year_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
