class Department < ActiveRecord::Base
  attr_accessible :abbr, :title, :number, :subdepartments_attributes

  belongs_to :year

  has_many :subdepartments, :dependent => :destroy

  accepts_nested_attributes_for :subdepartments
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: departments
#
# * id         :integer         not null
#   title      :string(255)
#   abbr       :string(255)
#   number     :integer
#   year_id    :integer
#   created_at :datetime        not null
#   updated_at :datetime        not null
#
#  Indexes:
#   index_departments_on_year_id  year_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
