class DidacticUnit < ActiveRecord::Base
  attr_accessible :content, :discipline

  belongs_to :gos

  validates_presence_of :content, :discipline

  alias_attribute :to_s, :discipline
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: didactic_units
#
# * id         :integer         not null
#   gos_id     :integer
#   discipline :string(255)
#   content    :text
#   created_at :datetime        not null
#   updated_at :datetime        not null
#
#  Indexes:
#   index_didactic_units_on_gos_id  gos_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
