class Discipline < ActiveRecord::Base
  attr_accessible :title

  belongs_to :subspeciality
  belongs_to :subdepartment

  validates_presence_of :title, :subspeciality, :subdepartment
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: disciplines
#
# * id               :integer         not null
#   title            :string(255)
#   cycle            :string(255)
#   subspeciality_id :integer
#   subdepartment_id :integer
#   created_at       :datetime        not null
#   updated_at       :datetime        not null
#
#  Indexes:
#   index_disciplines_on_subdepartment_id  subdepartment_id
#   index_disciplines_on_subspeciality_id  subspeciality_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
