class Exercise < ActiveRecord::Base
  attr_accessible :description, :title, :volume, :semester_id, :kind, :work_programm_id

  belongs_to :semester
  belongs_to :work_programm

  validates_presence_of :description, :title, :volume, :semester, :kind

  default_scope order('id ASC')

  has_enum :kind, [:lecture, :lab, :practice, :srs]
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: years
#
# * id         :integer         not null
#   number     :integer
#   deleted_at :datetime
#   created_at :datetime        not null
#   updated_at :datetime        not null
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
