#encoding: utf-8

class Gos < ActiveRecord::Base
  attr_accessible :code, :speciality, :approved_on

  has_many :didactic_units, :dependent => :destroy

  validates_presence_of :code, :speciality, :approved_on

  validates_uniqueness_of :code

  def to_s
    "#{code} — #{speciality}"
  end
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: goses
#
# * id          :integer         not null
#   speciality  :text
#   code        :string(255)
#   created_at  :datetime        not null
#   updated_at  :datetime        not null
#   approved_on :date
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
