class Lecture < ActiveRecord::Base
  attr_accessible :description, :title, :volume, :semester_id

  belongs_to :semester
  belongs_to :work_programm

  validates_presence_of :description, :title, :volume, :semester
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: lectures
#
# * id               :integer         not null
#   title            :string(255)
#   description      :text
#   volume           :integer
#   work_programm_id :integer
#   created_at       :datetime        not null
#   updated_at       :datetime        not null
#   semester_id      :integer
#
#  Indexes:
#   index_lectures_on_semester_id       semester_id
#   index_lectures_on_work_programm_id  work_programm_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
