class Loading < ActiveRecord::Base
  belongs_to :semester
  belongs_to :discipline
  attr_accessible :deleted_at, :kind, :value, :semester

  has_enum :kind
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: loadings
#
# * id            :integer         not null
#   semester_id   :integer
#   discipline_id :integer
#   kind          :string(255)
#   value         :integer
#   deleted_at    :datetime
#   created_at    :datetime        not null
#   updated_at    :datetime        not null
#
#  Indexes:
#   index_loadings_on_discipline_id  discipline_id
#   index_loadings_on_semester_id    semester_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
