class Person
  attr_accessor :post, :name, :science_post
  def initialize(name, post, science_post = "")
    self.post = post
    self.name = name
    self.science_post = science_post
  end

  def short_name
    "#{name.split(' ')[0]} #{name.split(' ')[1][0]}.#{name.split(' ')[2][0]}."
  end
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: departments
#
# * id         :integer         not null
#   title      :string(255)
#   abbr       :string(255)
#   number     :integer
#   year_id    :integer
#   deleted_at :datetime
#   created_at :datetime        not null
#   updated_at :datetime        not null
#
#  Indexes:
#   index_departments_on_year_id  year_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
