# encoding: utf-8

class Programm < ActiveRecord::Base
  belongs_to :subspeciality

end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: programms
#
# * id               :integer         not null
#   subspeciality_id :integer
#   description      :text
#   vfs_path         :string(255)
#   created_at       :datetime        not null
#   updated_at       :datetime        not null
#
#  Indexes:
#   index_programms_on_subspeciality_id  subspeciality_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
