class Semester < ActiveRecord::Base
  belongs_to :subspeciality
  attr_accessible :number
  validates_presence_of :subspeciality, :number
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: semesters
#
# * id               :integer         not null
#   subspeciality_id :integer
#   number           :integer
#   created_at       :datetime        not null
#   updated_at       :datetime        not null
#   deleted_at       :datetime
#
#  Indexes:
#   index_semesters_on_subspeciality_id  subspeciality_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
