class Speciality < ActiveRecord::Base
  attr_accessible :code, :title, :degree

  belongs_to :year

  has_many :subspecialities
  has_many :work_programms

  validates_presence_of :code, :title, :degree, :year

  after_save :move_subspeciality_to_trash, :if => [:deleted_at_changed?, :deleted_at?]

  def to_param
    code
  end

  private

  def move_subspeciality_to_trash
    subspecialities.update_all(:deleted_at => Time.now)
  end


end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: specialities
#
# * id         :integer         not null
#   code       :string(255)
#   title      :string(255)
#   degree     :string(255)
#   year_id    :integer
#   deleted_at :datetime
#   created_at :datetime        not null
#   updated_at :datetime        not null
#
#  Indexes:
#   index_specialities_on_year_id  year_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
