class Speciality < ActiveRecord::Base
  belongs_to :year
  attr_accessible :code, :title, :type
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: specialities
#
# * id         :integer         not null
#   code       :string(255)
#   title      :string(255)
#   type       :string(255)
#   year_id    :integer
#   created_at :datetime        not null
#   updated_at :datetime        not null
#
#  Indexes:
#   index_specialities_on_year_id  year_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
