class Speciality < ActiveRecord::Base
  attr_accessible :code, :title, :degree

  belongs_to :year

  has_many :subspecialities

  validates_presence_of :code, :title, :degree, :year

  def to_param
    code
  end
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: specialities
#
# * id         :integer         not null
#   code       :string(255)
#   title      :string(255)
#   degree     :string(255)
#   year_id    :integer
#   deleted_at :datetime
#   created_at :datetime        not null
#   updated_at :datetime        not null
#
#  Indexes:
#   index_specialities_on_year_id  year_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
