class Subdepartment < ActiveRecord::Base
  attr_accessible :abbr, :title, :number

  belongs_to :department
  has_many :subspecialities
  has_many :disciplines

  validates_presence_of :title, :abbr, :number, :department
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: subdepartments
#
# * id            :integer         not null
#   title         :string(255)
#   abbr          :string(255)
#   number        :integer
#   department_id :integer
#   deleted_at    :datetime
#   created_at    :datetime        not null
#   updated_at    :datetime        not null
#
#  Indexes:
#   index_subdepartments_on_department_id  department_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
