class Subdepartment < ActiveRecord::Base
  belongs_to :department
  attr_accessible :abbr, :title

  normalize_attribute :title

  def self.find_or_create_by_year_and_number(year, number)
    year = Year.find_or_create_by_number(year)
    title = title_by_number(number)
    department = year.departments.find_or_create_by_title(Department.title_by_subdepartment(title))
    department.subdepartments.find_or_create_by_title(title)
  end

  def self.title_by_number(number)
    start_offset = (number - 1) * 100
    end_offset = (number) * 100 - 1
    File.open("#{Rails.root}/data/DepNames.dat", 'r:cp1251').read[start_offset..end_offset]
  end
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: subdepartments
#
# * id            :integer         not null
#   title         :string(255)
#   abbr          :string(255)
#   department_id :integer
#   created_at    :datetime        not null
#   updated_at    :datetime        not null
#
#  Indexes:
#   index_subdepartments_on_department_id  department_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
