class Subdepartment < ActiveRecord::Base
  belongs_to :department
  attr_accessible :abbr, :name
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: subdepartments
#
# * id            :integer         not null
#   name          :string(255)
#   abbr          :string(255)
#   department_id :integer
#   created_at    :datetime        not null
#   updated_at    :datetime        not null
#
#  Indexes:
#   index_subdepartments_on_department_id  department_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
