# encoding: utf-8

class WorkProgramm < ActiveRecord::Base
  belongs_to :discipline
  attr_accessible :year
  validates_presence_of :discipline, :year

  default_value_for :year do  Time.now.year end
  validates_uniqueness_of :year, :scope => :discipline_id

  # FIXME: пока просто заглушка
  def authors
    [
      Person.new("Сидоров Анатолий Анатольевич", "Доцент каф. АОИ", "канд. экон. наук"),
      Person.new("Ехлаков Юрий Поликарпович", "Зав. кафедрой АОИ", "д-р техн. наук, профессор")
    ]
  end


end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: work_programms
#
# * id            :integer         not null
#   year          :integer
#   discipline_id :integer
#   created_at    :datetime        not null
#   updated_at    :datetime        not null
#
#  Indexes:
#   index_work_programms_on_discipline_id  discipline_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
